/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Tasks API
 * OpenAPI spec version: 1.0.0
 */
export type Get200 = {
  message: string;
};

export type GetPrizes200Item = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  text: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  amount: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  weight: number;
};

export type GetTwist200 = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  text: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  amount: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  weight: number;
};

export type GetMe200 = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  id: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  balance: number;
};

