/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Tasks API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPrizes200Item,
  GetTwist200
} from '../generated.schemas';

import { customFetch } from '.././mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getPrizesResponse200 = {
  data: GetPrizes200Item[]
  status: 200
}
    
export type getPrizesResponseSuccess = (getPrizesResponse200) & {
  headers: Headers;
};
;

export type getPrizesResponse = (getPrizesResponseSuccess)

export const getGetPrizesUrl = () => {


  

  return `http://localhost:3000/prizes`
}

export const getPrizes = async ( options?: RequestInit): Promise<getPrizesResponse> => {
  
  return customFetch<getPrizesResponse>(getGetPrizesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetPrizesQueryKey = () => {
    return [
    `http://localhost:3000/prizes`
    ] as const;
    }

    
export const getGetPrizesQueryOptions = <TData = Awaited<ReturnType<typeof getPrizes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrizes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPrizesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPrizes>>> = ({ signal }) => getPrizes({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPrizes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPrizesQueryResult = NonNullable<Awaited<ReturnType<typeof getPrizes>>>
export type GetPrizesQueryError = unknown


export function useGetPrizes<TData = Awaited<ReturnType<typeof getPrizes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrizes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrizes>>,
          TError,
          Awaited<ReturnType<typeof getPrizes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrizes<TData = Awaited<ReturnType<typeof getPrizes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrizes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPrizes>>,
          TError,
          Awaited<ReturnType<typeof getPrizes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPrizes<TData = Awaited<ReturnType<typeof getPrizes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrizes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPrizes<TData = Awaited<ReturnType<typeof getPrizes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPrizes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPrizesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export type getTwistResponse200 = {
  data: GetTwist200
  status: 200
}
    
export type getTwistResponseSuccess = (getTwistResponse200) & {
  headers: Headers;
};
;

export type getTwistResponse = (getTwistResponseSuccess)

export const getGetTwistUrl = () => {


  

  return `http://localhost:3000/twist`
}

export const getTwist = async ( options?: RequestInit): Promise<getTwistResponse> => {
  
  return customFetch<getTwistResponse>(getGetTwistUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTwistQueryKey = () => {
    return [
    `http://localhost:3000/twist`
    ] as const;
    }

    
export const getGetTwistQueryOptions = <TData = Awaited<ReturnType<typeof getTwist>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTwist>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTwistQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTwist>>> = ({ signal }) => getTwist({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTwist>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTwistQueryResult = NonNullable<Awaited<ReturnType<typeof getTwist>>>
export type GetTwistQueryError = unknown


export function useGetTwist<TData = Awaited<ReturnType<typeof getTwist>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTwist>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTwist>>,
          TError,
          Awaited<ReturnType<typeof getTwist>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTwist<TData = Awaited<ReturnType<typeof getTwist>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTwist>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTwist>>,
          TError,
          Awaited<ReturnType<typeof getTwist>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTwist<TData = Awaited<ReturnType<typeof getTwist>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTwist>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTwist<TData = Awaited<ReturnType<typeof getTwist>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTwist>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTwistQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




